ETH_INTERFACE_NAME=enp5s0
WLAN_INTERFACE_NAME=wlo1
ETH_STATIC_IP=192.0.2.1

sysctl -w net.ipv4.ip_forward=1
ip address add dev $ETH_INTERFACE_NAME $ETH_STATIC_IP/24
iptables -t nat -A POSTROUTING -o $WLAN_INTERFACE_NAME -j MASQUERADE
iptables -A FORWARD -i $ETH_INTERFACE_NAME -o $WLAN_INTERFACE_NAME -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i $WLAN_INTERFACE_NAME -o $ETH_INTERFACE_NAME -j ACCEPT
