manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: kamufladge
      url-base: ssh://git@github.com/kamufladge
  defaults:
    remote: kamufladge
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.0.0
      import:
        name-allowlist:
          - babblesim_base
          - cmsis
          - hal_stm32
  self:
    path: application
